theme: jekyll-theme-architect
imgdir: 'assets/img/gallery'
baseurl: '/'
title: Zita Spa
email: apaiva78@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  For many bathing is an alone moment,
  their time to find fulfillment in relaxation,
  It's not just about cleansing,
  It's about treating yourself to something special
  We're all about beautiful skin and happy minds
